<?php
/**
 * Default Pages Manager
 *
 * Responsible for creating a default set of pages.
 *
 * @since 0.4.0
 * @package ecommerce-store-optimizer
 */

declare(strict_types=1);

namespace Genesis\EcommerceStoreOptimizer\Modules\DefaultPages;

/**
 * Customizer Defaults Manager class
 *
 * @since 0.4.0
 */
final class DefaultPagesManager {

	/**
	 * Create a new page.
	 *
	 * Runs on plugin install
	 *
	 * @since 1.0
	 *
	 * @param mixed $context Plugin context.
	 */
	public function create_default_pages( $context = null ) {

		$all_patterns = $this->get_registered_patterns();

		// Define the page we want to create.
		$pages = [
			'eso_home'                      => [
				'title'         => __( 'Home', 'ecommerce-store-optimizer' ),
				'content'       => $this->set_categories_for_woo_blocks_in_homepage( $all_patterns['eso_spend_layout_homepage']['content'] ),
				'add_to_menu'   => true,
				'menu_position' => 1,
				'is_front_page' => true,
				'page_template' => 'blocks.php',
			],
			'eso_shop_info'                 => [
				'title'         => __( 'About', 'ecommerce-store-optimizer' ),
				'content'       => $all_patterns['eso_spend_layout_shop_info']['content'],
				'add_to_menu'   => true,
				'menu_position' => 2,
				'page_template' => 'blocks.php',
			],
			// Woo Shop Page. This page is generated by WooCommerce here: https://github.com/woocommerce/woocommerce/blob/593cd0ea5d38f641230e7904d9baa1f00d7d0e63/includes/class-wc-install.php#L555.
			'woocommerce_shop_page_id'      => array(
				'title'         => _x( 'Shop', 'Page title', 'ecommerce-store-optimizer' ),
				'content'       => '',
				'add_to_menu'   => true,
				'menu_position' => 3,
			),
			// Woo Account Page. This page is generated by WooCommerce here: https://github.com/woocommerce/woocommerce/blob/593cd0ea5d38f641230e7904d9baa1f00d7d0e63/includes/class-wc-install.php#L573.
			'woocommerce_myaccount_page_id' => [
				'title'         => __( 'My Account', 'ecommerce-store-optimizer' ),
				'content'       => '<!-- wp:shortcode -->[' . apply_filters( 'woocommerce_my_account_shortcode_tag', 'woocommerce_my_account' ) . ']<!-- /wp:shortcode -->',
				'add_to_menu'   => true,
				'menu_position' => 4,
			],
			// Woo Cart Page. This page is generated by WooCommerce here: https://github.com/woocommerce/woocommerce/blob/593cd0ea5d38f641230e7904d9baa1f00d7d0e63/includes/class-wc-install.php#L560.
			'woocommerce_cart_page_id'      => array(
				'title'         => _x( 'Cart', 'Page title', 'ecommerce-store-optimizer' ),
				'content'       => '<!-- wp:shortcode -->[' . apply_filters( 'woocommerce_cart_shortcode_tag', 'woocommerce_cart' ) . ']<!-- /wp:shortcode -->',
				'add_to_menu'   => true,
				'menu_position' => 5,
			),
			// Woo Checkout Page. This page is generated by WooCommerce here: https://github.com/woocommerce/woocommerce/blob/593cd0ea5d38f641230e7904d9baa1f00d7d0e63/includes/class-wc-install.php#L565.
			'woocommerce_checkout_page_id'  => array(
				'title'         => _x( 'Checkout', 'Page title', 'ecommerce-store-optimizer' ),
				'content'       => '<!-- wp:shortcode -->[' . apply_filters( 'woocommerce_checkout_shortcode_tag', 'woocommerce_checkout' ) . ']<!-- /wp:shortcode -->',
				'add_to_menu'   => true,
				'menu_position' => 6,
			),
		];

		$menu_name = __( 'Main Navigation', 'ecommerce-store-optimizer' );

		// Check if a menu already exists with this name.
		$possible_existing_menu = get_term_by( 'name', $menu_name, 'nav_menu' );

		// This makes sure we don't create tons of duplicate menus, but only one. If we want to change that, bypass this if statement.
		if (
			$possible_existing_menu &&
			! is_wp_error( $possible_existing_menu ) &&
			isset( $possible_existing_menu->term_id )
		) {
			// If this menu exists, set the menu id to the existing.
			$menu_id = $possible_existing_menu->term_id;
		} else {
			// Spin up a new navigation menu.
			$menu_id = wp_create_nav_menu( __( 'Main Navigation', 'ecommerce-store-optimizer' ) );
		}

		// Set this menu to appear in the default location.
		$locations            = get_theme_mod( 'nav_menu_locations' );
		$locations['primary'] = $menu_id;
		set_theme_mod( 'nav_menu_locations', $locations );

		foreach ( $pages as $page_key => $page ) {

			// If this page already exists, skip it.
			$page_id_already_exists = get_option( $page_key );
			$page_already_exists    = get_post( $page_id_already_exists );

			// (Re)Create this page if it doesn't exist.
			if ( empty( $page_already_exists->ID ) ) {

				$page_creation_args = array(
					'post_author'    => '1',
					'post_content'   => $page['content'],
					'post_title'     => $page['title'],
					'post_status'    => 'publish',
					'comment_status' => 'closed',
					'ping_status'    => 'closed',
					'post_type'      => 'page',
				);

				// Insert the post into the database.
				$page_id = wp_insert_post( $page_creation_args );

				// Save the ID so we know not to overwrite it with subsequent runs.
				update_option( $page_key, $page_id );
			} else {
				$page_id = $page_already_exists->ID;
			}

			// Make sure we have an integer.
			$page_id = absint( $page_id );

			// Set the page template.
			if ( isset( $page['page_template'] ) && ! empty( $page['page_template'] ) ) {
				update_post_meta( $page_id, '_wp_page_template', $page['page_template'] );
			}

			// If this page should be added to a menu, add it to a menu.
			if ( $page['add_to_menu'] && ! empty( $page_id ) ) {
				$existing_menu_items  = wp_get_nav_menu_items( $menu_id );
				$page_already_on_menu = false;

				foreach ( $existing_menu_items as $existing_menu_item ) {
					// Check if this page is already on the menu. If it is, don't duplicate it on the menu.
					if ( absint( $existing_menu_item->object_id ) === absint( $page_id ) ) {
						$page_already_on_menu = true;
					}
				}

				// Add this page to the menu, if it doesn't already exist on the menu.
				if ( ! $page_already_on_menu ) {
					wp_update_nav_menu_item(
						$menu_id,
						0,
						array(
							'menu-item-title'     => $page['title'],
							'menu-item-object-id' => $page_id,
							'menu-item-object'    => 'page',
							'menu-item-status'    => 'publish',
							'menu-item-position'  => $page['menu_position'],
							'menu-item-type'      => 'post_type',
						)
					);
				}
			}

			// If this page is the homepage, set it to show on the front of the site.
			if ( isset( $page['is_front_page'] ) && $page['is_front_page'] ) {
				update_option( 'show_on_front', 'page', true );
				update_option( 'page_on_front', $page_id, true );
			}
		}

	}

	/**
	 * Get all patterns available in Genesis Blocks.
	 *
	 * @since  1.0.0
	 * @return array
	 */
	private function get_registered_patterns() {
		$layouts            = genesis_blocks_get_layouts();
		$sections           = genesis_blocks_get_sections();
		$additional_layouts = apply_filters( 'genesis_blocks_additional_layout_components', [] );
		$patterns           = array_merge( $layouts, $sections, $additional_layouts );

		// Apply the key to each pattern so they are easier to reference.
		foreach ( $patterns as $pattern ) {
			$patterns_with_keys[ $pattern['key'] ] = $pattern;
		}

		return $patterns_with_keys;

	}

	/**
	 * Set the demo categories for the featured category blocks on that passed-in pattern code.
	 *
	 * @since  1.0.0
	 * @param string $pattern The pattern code which needs the categories to be set.
	 * @return string
	 */
	private function set_categories_for_woo_blocks_in_homepage( $pattern ) {

		// Get the demo categories.
		$demo_categories = $this->get_demo_product_categories();

		// Loop through each product category id.
		foreach ( $demo_categories as $demo_category ) {
			if (
				't-shirts' === $demo_category->meta_value ||
				'hoodies' === $demo_category->meta_value ||
				'hats' === $demo_category->meta_value
			) {
				// Replace the first featured category block with the term ID for t-shirts.
				$pattern = $this->replace_first_instance_in_string( '<!-- wp:woocommerce/featured-category /-->', '<!-- wp:woocommerce/featured-category {"editMode":false,"categoryId":' . $demo_category->term_id . '} /-->', $pattern );
			}
		}

		return $pattern;
	}

	/**
	 * Find and replace the first (and only the first) instance of a string in a string.
	 *
	 * @since  1.0.0
	 * @param string $find The string to replace.
	 * @param string $replace This is what will replace the $find string.
	 * @param string $haystack The string which is searched, and in which the $find is replaced with the value in $replace.
	 * @return string
	 */
	private function replace_first_instance_in_string( $find, $replace, $haystack ) {
		$pos = strpos( $haystack, $find );
		if ( $pos !== false ) {
			$newstring = substr_replace( $haystack, $replace, $pos, strlen( $find ) );
			return $newstring;
		}
		return $haystack;
	}

	/**
	 * Get Demo Product IDs
	 */
	private function get_demo_product_categories() {
		global $wpdb;

		// Tables.
		$term_taxonomy_table_name = $wpdb->term_taxonomy;
		$term_meta_table_name     = $wpdb->termmeta;

		// Join IDs.
		$term_taxonomy_table_term_id = $wpdb->term_taxonomy . '.term_id';
		$term_meta_table_term_id     = $wpdb->termmeta . '.term_id';

		// Meta table key.
		$term_meta_key = $wpdb->termmeta . '.meta_key';

		// Get the Demo categories.
		$query   = "SELECT *
		FROM $term_taxonomy_table_name
		INNER JOIN $term_meta_table_name ON $term_taxonomy_table_term_id = $term_meta_table_term_id
		WHERE $term_meta_key = %s
		";
		$prep    = $wpdb->prepare( $query, 'wpe_democat_slug' ); /* phpcs:ignore */
		$results = $wpdb->get_results( $prep ); /* phpcs:ignore */

		return $results;

	}
}
